apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xwcg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xwcg
    app.kubernetes.io/part-of: tkrw-pr712-0075-0015-app
  name: devfile-sample-xwcg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xwcg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xwcg
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0015-tenant/tkrw-pr712-0075-0015-app/devfile-sample-xwcg@sha256:f7742f4ad0bc0f915596dd3d0931f5e803e84758c2d0b1999eda1307f547567b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
